/* Neighborhood evidence ranking. No physical condition is inferred as confirmed. */
(function(root){'use strict';
function isOpen(r){return /^open$/i.test(r.status||'')}
function isClosed(r){return /^(completed|closed)$/i.test(r.status||'')}
function validPoint(r){return r.latitude!=null&&r.longitude!=null&&r.latitude!==''&&r.longitude!==''&&Number.isFinite(Number(r.latitude))&&Number.isFinite(Number(r.longitude))&&Math.abs(Number(r.latitude))<=90&&Math.abs(Number(r.longitude))<=180}
function clean(rows){var seen=new Set();return (rows||[]).filter(function(r){var id=r.sr_number||r.crash_record_id;if(r.duplicate===true||r.duplicate==='true'||!validPoint(r)||id&&seen.has(id))return false;if(id)seen.add(id);return true})}
function dist(a,b,c,d){var R=6371000,p=Math.PI/180,x=(d-b)*p*Math.cos((a+c)*p/2),y=(c-a)*p;return Math.sqrt(x*x+y*y)*R}
function daysOld(v){var d=new Date(v);return isNaN(d.getTime())?0:Math.max(0,(Date.now()-d.getTime())/86400000)}
function dateLabel(v){var d=new Date(v);return isNaN(d.getTime())?'Unknown':d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}
function cluster(rows,meters){var groups=[];rows.forEach(function(r){var lat=Number(r.latitude),lon=Number(r.longitude);if(!validPoint(r))return;var g=null;for(var i=0;i<groups.length;i++){if(dist(lat,lon,groups[i].lat,groups[i].lon)<=meters){g=groups[i];break}}if(!g){g={lat:lat,lon:lon,rows:[]};groups.push(g)}g.rows.push(r);var n=g.rows.length;g.lat=(g.lat*(n-1)+lat)/n;g.lon=(g.lon*(n-1)+lon)/n});return groups}
function streetLabel(r){return [r.street_number||r.street_no,r.street_direction,r.street_name,r.street_type].filter(Boolean).join(' ')||'this location'}
function buildObservations(data){var out=[],trees=clean(data.trees),graffiti=clean(data.graffiti),rats=clean(data.rats),crashes=clean(data.crashes);
var removals=trees.filter(function(r){return r.sr_type==='Tree Removal Inspection' && isClosed(r)});var plantings=trees.filter(function(r){return r.sr_type==='Tree Planting Request'});
removals.forEach(function(r){var age=daysOld(r.closed_date||r.created_date);if(age<180)return;var lat=Number(r.latitude),lon=Number(r.longitude);if(!validPoint(r))return;var matched=plantings.some(function(p){return validPoint(p)&&dist(lat,lon,Number(p.latitude),Number(p.longitude))<=50&&(isOpen(p)||(isClosed(p)&&new Date(p.closed_date||p.created_date)>=new Date(r.closed_date||r.created_date)))});if(!matched){out.push({kind:'tree',type:'gap',lat:lat,lon:lon,score:65+Math.min(25,age/30),title:'Possible tree replacement gap',why:'A tree-removal inspection closed '+Math.round(age/30)+' months ago. No open planting request or later completed planting record was found within 50 meters in the loaded history. The inspection may not have resulted in removal.',metric:Math.round(age/30)+' months',metricLabel:'since inspection closed',confidence:'Medium',action:'Confirm whether the site is empty. Recheck existing requests before asking Forestry for a planting assessment.',evidence:[r]})}});
plantings.filter(function(r){return isOpen(r)}).forEach(function(r){var age=daysOld(r.created_date);if(age<365)return;var lat=Number(r.latitude),lon=Number(r.longitude);if(!validPoint(r))return;out.push({kind:'tree',type:'stale',lat:lat,lon:lon,score:55+Math.min(35,age/45),title:'Tree planting request open over a year',why:'This planting request has remained open for about '+Math.round(age/30)+' months.',metric:Math.round(age/30)+' months',metricLabel:'open',confidence:'High',action:'Check the request status and consider escalating if the site still needs a tree.',evidence:[r]})});
var gClusters=cluster(graffiti,55).filter(function(g){return g.rows.length>=4}).sort(function(a,b){return b.rows.length-a.rows.length});gClusters.slice(0,4).forEach(function(g,i){var open=g.rows.filter(function(r){return isOpen(r)}).length;out.push({kind:'graffiti',type:'recurring',lat:g.lat,lon:g.lon,score:58+Math.min(32,g.rows.length*4)+Math.min(10,open*2),title:i===0?'Highest recurring graffiti activity nearby':'Recurring graffiti location',why:g.rows.length+' graffiti-related reports were filed in this small area during the last 90 days'+(open?'; '+open+' are still open.':'.'),metric:g.rows.length+' reports',metricLabel:'last 90 days',confidence:'Medium',action:'Inspect the hotspot. Repeated reporting after prior closures may point to a location needing a more durable intervention.',evidence:g.rows})});
var rClusters=cluster(rats,65).filter(function(g){return g.rows.length>=4}).sort(function(a,b){return b.rows.length-a.rows.length});rClusters.slice(0,4).forEach(function(g,i){var open=g.rows.filter(function(r){return isOpen(r)}).length;out.push({kind:'rat',type:'recurring',lat:g.lat,lon:g.lon,score:56+Math.min(34,g.rows.length*4)+Math.min(10,open*2),title:i===0?'Strongest recurring rat signal nearby':'Persistent rat-report cluster',why:g.rows.length+' rodent-related reports cluster here in the last 90 days'+(open?'; '+open+' are still open.':'.'),metric:g.rows.length+' reports',metricLabel:'last 90 days',confidence:'Medium',action:'Look for recurring sanitation or property conditions around the cluster rather than treating each report as an isolated event.',evidence:g.rows})});
var cClusters=cluster(crashes,75).filter(function(g){return g.rows.length>=3}).sort(function(a,b){function w(x){return x.rows.reduce(function(s,r){var severe=Number(r.injuries_fatal||0)*5+Number(r.injuries_incapacitating||0)*3;return s+1+severe},0)}return w(b)-w(a)});cClusters.slice(0,4).forEach(function(g,i){var serious=g.rows.reduce(function(s,r){return s+Number(r.injuries_fatal||0)+Number(r.injuries_incapacitating||0)},0);out.push({kind:'bike',type:'safety',lat:g.lat,lon:g.lon,score:68+Math.min(24,g.rows.length*3)+Math.min(18,serious*5),title:i===0?'Most crash-prone bike area nearby':'Repeated bike-crash area',why:g.rows.length+' pedalcyclist crashes cluster here over the last five years'+(serious?'; '+serious+' involved fatal or incapacitating injuries.':'.'),metric:g.rows.length+' crashes',metricLabel:'last 5 years',confidence:'High',action:'Review the intersection design and recent crash pattern. This is a candidate for a specific safety intervention.',evidence:g.rows})});
return out.map(function(o){o.score=Math.min(100,o.score);return o}).sort(function(a,b){return b.score-a.score})}
function diversifiedTop(list,n){var chosen=[],counts={};for(var i=0;i<list.length&&chosen.length<n;i++){var o=list[i],cap=o.kind==='tree'?2:1;if((counts[o.kind]||0)>=cap)continue;if(o.score<64)continue;chosen.push(o);counts[o.kind]=(counts[o.kind]||0)+1}return chosen}

var api={buildObservations:buildObservations,diversifiedTop:diversifiedTop};if(typeof module!=='undefined')module.exports=api;else root.NeighborhoodSignals=api;
})(typeof window!=='undefined'?window:globalThis);
